// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// write_fimpute_cpp
void write_fimpute_cpp(CharacterMatrix geno_mat, CharacterVector ids, std::string file_path);
RcppExport SEXP _SNPtools_write_fimpute_cpp(SEXP geno_matSEXP, SEXP idsSEXP, SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type geno_mat(geno_matSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    write_fimpute_cpp(geno_mat, ids, file_path);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SNPtools_write_fimpute_cpp", (DL_FUNC) &_SNPtools_write_fimpute_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SNPtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
