# .github/workflows/R-CMD-check.yaml
name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: macOS-latest

    strategy:
      matrix:
        config:
          - { os: windows-latest, r: 'release' }
          - { os: macOS-latest,  r: 'release' }
          - { os: ubuntu-latest, r: 'release' }

    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install dependencies
        run: Rscript -e 'install.packages(c("devtools", "rcmdcheck"))'

      - name: Check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "error")'
